[package]
name = "evalrus"
version = "0.0.1"
authors = ["Peter Liniker <peter.liniker+github@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0"
fnv = "1.0.3"
itertools = "0.9"
rustyline = "17.0"
immixcons = { path = "../immixcons" }
blockalloc = { path = "../blockalloc" }
