on: [push, pull_request]
#  push: 
#    branches: [master]
#  pull_request: 
#    branches: [master]

name: code-test

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Use latest stable
        run: rustup update stable

      - name: Cargo fmt check blockalloc
        working-directory: ./blockalloc
        run: cargo fmt --all -- --check

      - name: Cargo fmt check immixcons
        working-directory: ./immixcons
        run: cargo fmt --all -- --check

      - name: Cargo fmt check interpreter
        working-directory: ./interpreter
        run: cargo fmt --all -- --check

      - name: Cargo test blockalloc
        working-directory: ./blockalloc
        run: cargo test

      - name: Cargo test immixcons
        working-directory: ./immixcons
        run: cargo test

      - name: Cargo test interpreter
        working-directory: ./interpreter
        run: cargo test
